import { expect, test } from '@playwright/test'
import sharp from 'sharp'

test.use({ baseURL: `http://127.0.0.1:${Number(process.env.ATLAS_TEST_PORT || 8106) + 1}` })

test('code-only login protects the board, remembers access, and signs out', async ({ page, context, browser }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Small human. Big welcome.' })).toBeVisible()
  await expect(page.locator('#love-board')).toHaveCount(0)
  await expect(page.locator('input')).toHaveCount(1)
  await page.getByLabel('Team invite code').fill('wrong')
  await page.getByRole('button', { name: 'Come on in' }).click()
  await expect(page.getByRole('alert')).toContainText("isn't quite right")
  await page.getByLabel('Team invite code').fill('browser-test-invite')
  await page.getByRole('button', { name: 'Show code' }).click()
  await expect(page.getByLabel('Team invite code')).toHaveAttribute('type', 'text')
  await page.getByRole('button', { name: 'Hide code' }).click()
  await page.getByLabel('Team invite code').press('Enter')
  await expect(page.locator('#love-board')).toBeVisible()
  const cookies = await context.cookies()
  expect(cookies.find((cookie) => cookie.name === 'atlas-session')?.httpOnly).toBe(true)
  expect(await page.evaluate(() => document.cookie)).not.toContain('atlas-session')
  expect(await page.evaluate(() => JSON.stringify([localStorage, sessionStorage]))).not.toContain('browser-test-invite')
  await page.reload()
  await expect(page.locator('#love-board')).toBeVisible()
  await page.getByRole('button', { name: 'Leave a little love', exact: true }).click()
  await expect(page.getByLabel('Team invite code')).toHaveCount(0)
  await page.getByLabel('Your name', { exact: true }).fill('Invited Guest')
  await page.getByLabel('Your little love note').fill('A little love behind the invitation.')
  const photo = await sharp({ create: { width: 30, height: 30, channels: 3, background: '#e99a80' } }).png().toBuffer()
  await page.getByLabel('Choose a photo').setInputFiles({ name: 'memory.png', mimeType: 'image/png', buffer: photo })
  await page.getByRole('button', { name: 'Send a little love', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const card = page.locator('article').filter({ hasText: 'Invited Guest' }).first()
  await expect(card.locator('img')).toBeVisible()
  await expect.poll(() => card.locator('img').evaluate((image: HTMLImageElement) => image.naturalWidth)).toBeGreaterThan(0)
  const photoPath = await card.locator('img').getAttribute('src')
  const stranger = await browser.newContext()
  expect((await stranger.request.get(new URL('/api/messages', page.url()).href)).status()).toBe(401)
  expect((await stranger.request.get(new URL(photoPath!, page.url()).href)).status()).toBe(401)
  await stranger.close()
  await card.locator('.heart-button').click()
  await expect(card.locator('.heart-button')).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page.getByLabel('Team invite code')).toBeVisible()
  expect((await context.request.get('/api/messages')).status()).toBe(401)
  await page.reload()
  await expect(page.getByLabel('Team invite code')).toBeVisible()
})

test('expired sessions return to the code screen and preserve note text', async ({ page, context }) => {
  await page.goto('/')
  await page.getByLabel('Team invite code').fill('browser-test-invite')
  await page.getByRole('button', { name: 'Come on in' }).click()
  await page.getByRole('button', { name: 'Leave a little love', exact: true }).click()
  await page.getByLabel('Your name', { exact: true }).fill('Returning Guest')
  await page.getByLabel('Your little love note').fill('Keep this little thought safe.')
  await context.clearCookies()
  await page.getByRole('button', { name: 'Send a little love', exact: true }).click()
  await expect(page.getByLabel('Team invite code')).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('note text is saved')
  await page.getByLabel('Team invite code').fill('browser-test-invite')
  await page.getByRole('button', { name: 'Come on in' }).click()
  await page.getByRole('button', { name: 'Leave a little love', exact: true }).click()
  await expect(page.getByLabel('Your little love note')).toHaveValue('Keep this little thought safe.')
})

test('unreachable server does not expose the board and can be retried', async ({ page }) => {
  await page.route('**/api/session', (route) => route.abort())
  await page.goto('/')
  await expect(page.getByRole('alert')).toContainText('tiny breather')
  await expect(page.locator('#love-board')).toHaveCount(0)
  await page.unroute('**/api/session')
  await page.getByRole('button', { name: 'Try again', exact: true }).click()
  await expect(page.getByLabel('Team invite code')).toBeVisible()
})

for (const width of [1440, 390, 320]) {
  test(`invitation screen fits at ${width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: width === 1440 ? 900 : 844 })
    await page.goto('/')
    await expect(page.getByLabel('Team invite code')).toBeVisible()
    await page.evaluate(() => document.fonts.ready)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`invitation-${width}.png`), fullPage: true })
  })
}