import { expect, test } from '@playwright/test'
import sharp from 'sharp'

test('the welcome, notes, and sharing celebrate Natalie and Duke together', async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(navigator, 'share', { configurable: true, value: async (data: ShareData) => {
      document.documentElement.dataset.sharedText = data.text
    } })
  })
  await page.goto('/')
  await expect(page.locator('.hero-bottom')).toContainText('Natalie & Duke')
  await expect(page.locator('.hero-bottom')).toContainText('so happy for you both')
  await expect(page.locator('.board-heading')).toContainText('For Atlas, Natalie & Duke')
  await expect(page.locator('.team-note')).toContainText('Natalie and Duke')
  await expect(page.locator('.team-signature')).toContainText("Duke's work fam, cheering for you all")
  await expect(page.locator('.dedication')).toContainText("NATALIE & DUKE, THIS ONE'S FOR YOU")
  await expect(page.locator('.dedication')).toContainText("We're cheering you both on.")
  await expect(page.locator('meta[name="description"]')).toHaveAttribute('content', /Natalie & Duke/)
  await expect(page.locator('meta[property="og:description"]')).toHaveAttribute('content', /Atlas, Natalie & Duke/)
  await expect(page.locator('body')).not.toContainText(/your dad|coolest dad|NOTE FOR DAD/)
  await page.getByRole('button', { name: 'Invite more love' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-shared-text', /Atlas, Natalie & Duke/)
  await page.getByRole('button', { name: 'Leave a little love', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('the whole crew.')
  await expect(page.locator('.composer-preview')).toContainText('FOR ATLAS, NATALIE & DUKE')
  await expect(page.getByLabel('Your little love note')).toHaveAttribute('placeholder', 'Hey Natalie, Duke & little Atlas...')
})

test('a photo note is shared, reloads, receives hearts, and can be found', async ({ page, browser }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Atlas', exact: true })).toBeAttached()
  await expect(page.locator('.loading-notes')).toHaveCount(0)
  await page.getByRole('button', { name: 'Leave a little love', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Send a little love', exact: true })).toBeDisabled()
  await page.getByLabel('Your name', { exact: true }).fill('Browser Test Guest')
  await page.getByLabel('Your little love note').fill('Hey Atlas, a whole world of adventures is waiting for you!')
  await page.getByRole('radio', { name: 'blue paper' }).check()
  await page.getByRole('radio', { name: 'star sticker' }).check()
  await page.getByLabel('Choose a photo').setInputFiles({ name: 'not-a-photo.txt', mimeType: 'text/plain', buffer: Buffer.from('not a photo') })
  await expect(page.getByRole('alert')).toContainText('JPG, PNG, or WebP')
  const photo = await sharp({ create: { width: 500, height: 350, channels: 3, background: '#e99a80' } }).png().toBuffer()
  await page.getByLabel('Choose a photo').setInputFiles({ name: 'memory.png', mimeType: 'image/png', buffer: photo })
  await expect(page.getByAltText('Selected upload')).toBeVisible()
  await page.getByRole('button', { name: 'Send a little love', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const card = page.locator('article').filter({ hasText: 'Browser Test Guest' })
  await expect(card).toContainText('a whole world of adventures')
  await expect(card).toHaveClass(/paper-blue/)
  await expect(card.locator('img')).toBeVisible()
  await card.getByRole('button', { name: 'Open photo from Browser Test Guest' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await card.getByRole('button', { name: "Send love to Browser Test Guest's note" }).click()
  await expect(card.locator('.heart-button')).toHaveAttribute('aria-pressed', 'true')
  await expect(card.locator('.heart-button')).toContainText('1')
  await page.reload()
  await expect(card).toBeVisible()
  await expect(card.locator('.heart-button')).toHaveAttribute('aria-pressed', 'true')
  const anotherGuest = await browser.newContext()
  const otherPage = await anotherGuest.newPage()
  await otherPage.goto(new URL('/', page.url()).href)
  await expect(otherPage.getByText('Browser Test Guest', { exact: true })).toBeVisible()
  await expect(otherPage.locator('.note-photo img')).toBeVisible()
  await anotherGuest.close()
  await page.getByRole('button', { name: /^With photos/ }).click()
  await expect(card).toBeVisible()
  await expect(page.locator('.team-note')).toHaveCount(0)
  await page.getByRole('searchbox', { name: 'Search notes' }).fill('not-a-person')
  await expect(page.getByRole('heading', { name: 'No notes found, little detective.' })).toBeVisible()
  await page.getByRole('button', { name: 'Clear search' }).click()
  await expect(card).toBeVisible()
  await page.getByRole('combobox', { name: 'Sort notes' }).selectOption('oldest')
  await expect(card).toBeVisible()
  await card.locator('.heart-button').click()
  await expect(card.locator('.heart-button')).toContainText('0')
  expect(errors).toEqual([])
})

test('a failed save keeps the note and lets the guest retry', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Leave a little love', exact: true }).click()
  await page.getByLabel('Your name', { exact: true }).fill('Retry Guest')
  await page.getByLabel('Your little love note').fill('This little note should never disappear on a failed save.')
  await page.route('**/api/messages', (route) => route.request().method() === 'POST' ? route.abort() : route.continue())
  await page.getByRole('button', { name: 'Send a little love', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText("Can't reach")
  await expect(page.getByLabel('Your little love note')).toHaveValue('This little note should never disappear on a failed save.')
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Leave a little love', exact: true }).click()
  await expect(page.getByLabel('Your name', { exact: true })).toHaveValue('Retry Guest')
  await page.unroute('**/api/messages')
  await page.getByRole('button', { name: 'Send a little love', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByText('Retry Guest', { exact: true })).toBeVisible()
})

for (const viewport of [{ width: 1440, height: 1000 }, { width: 1920, height: 1080 }, { width: 390, height: 844 }, { width: 320, height: 740 }]) {
  test(`3D scene and layout at ${viewport.width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize(viewport)
    await page.goto('/')
    await expect(page.locator('.hero-scene.is-ready')).toBeVisible()
    await expect(page.locator('.hero-canvas')).toHaveAttribute('data-inflation', '100,100,100,100,100')
    await page.evaluate(() => document.fonts.ready)
    await expect.poll(() => page.locator('.hero-scene canvas').evaluate((canvas: HTMLCanvasElement) => {
      const gl = canvas.getContext('webgl2')!
      const pixels = new Uint8Array(canvas.width * canvas.height * 4)
      gl.readPixels(0, 0, canvas.width, canvas.height, gl.RGBA, gl.UNSIGNED_BYTE, pixels)
      let colored = 0
      for (let offset = 3; offset < pixels.length; offset += 4) if (pixels[offset] > 100) colored++
      return colored / (canvas.width * canvas.height)
    })).toBeGreaterThan(0.025)
    const initial = await page.locator('.hero-scene canvas').evaluate((canvas: HTMLCanvasElement) => canvas.toDataURL())
    await page.mouse.move(viewport.width * 0.8, 260)
    await expect.poll(() => page.locator('.hero-scene canvas').evaluate((canvas: HTMLCanvasElement) => canvas.toDataURL())).not.toBe(initial)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const title = await page.locator('.hero-bottom h2').boundingBox()
    const scene = await page.locator('.scene-wrap').boundingBox()
    expect(title!.y).toBeGreaterThanOrEqual(scene!.y + scene!.height - 10)
    expect(await page.locator('.party-ribbon').evaluate((element) => element.getBoundingClientRect().bottom)).toBeLessThan(viewport.height)
    await page.screenshot({ path: testInfo.outputPath(`atlas-${viewport.width}.png`), fullPage: true })
    await page.getByRole('button', { name: 'Leave a little love', exact: true }).click()
    await page.getByLabel('Your name', { exact: true }).fill('A name with lots of letters that still fits beautifully')
    await page.getByLabel('Your little love note').fill('Welcome little Atlas! '.repeat(20))
    const dialog = page.getByRole('dialog')
    expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`composer-${viewport.width}.png`) })
    await page.keyboard.press('Escape')
    await expect(dialog).toHaveCount(0)
  })
}

test('reduced motion and keyboard dialog focus work', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.locator('.hero-scene.is-ready')).toBeVisible()
  await expect(page.locator('.site')).toHaveClass(/motion-paused/)
  await expect(page.locator('.hero-canvas')).toHaveAttribute('data-inflation', '100,100,100,100,100')
  await expect(page.getByRole('button', { name: 'Replay balloon inflation' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Turn animations on' })).toBeDisabled()
  const initial = await page.locator('.hero-scene canvas').evaluate((canvas: HTMLCanvasElement) => canvas.toDataURL())
  await page.getByRole('button', { name: 'Celebrate Atlas' }).click()
  await expect(page.getByRole('status')).toContainText('All the love')
  const after = await page.locator('.hero-scene canvas').evaluate((canvas: HTMLCanvasElement) => canvas.toDataURL())
  expect(after).toBe(initial)
  const opener = page.getByRole('button', { name: 'Leave a little love', exact: true })
  await opener.click()
  await page.keyboard.press('Tab')
  expect(await page.evaluate(() => Boolean(document.activeElement?.closest('dialog')))).toBe(true)
  await page.keyboard.press('Escape')
  await expect(opener).toBeFocused()
})

test('resizing an inactive tab does not erase the 3D welcome', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.hero-scene.is-ready')).toBeVisible()
  await page.evaluate(() => Object.defineProperty(document, 'hidden', { configurable: true, get: () => true }))
  await page.setViewportSize({ width: 1000, height: 800 })
  await expect.poll(() => page.locator('.hero-scene canvas').evaluate((canvas: HTMLCanvasElement) => {
    const gl = canvas.getContext('webgl2')!
    const pixels = new Uint8Array(canvas.width * canvas.height * 4)
    gl.readPixels(0, 0, canvas.width, canvas.height, gl.RGBA, gl.UNSIGNED_BYTE, pixels)
    return pixels.some((value, index) => index % 4 === 3 && value > 100)
  })).toBe(true)
})

test('slow loading reveals the complete scene once without replacement lettering', async ({ page }, testInfo) => {
  let releaseChunk!: () => void
  let releaseFont!: () => void
  let fontRequested!: () => void
  const chunkGate = new Promise<void>((resolve) => { releaseChunk = resolve })
  const fontGate = new Promise<void>((resolve) => { releaseFont = resolve })
  const fontRequest = new Promise<void>((resolve) => { fontRequested = resolve })
  await page.route('**/assets/HeroScene-*.js', async (route) => {
    await chunkGate
    await route.continue()
  })
  await page.route('**/balloon-font.json', async (route) => {
    fontRequested()
    await fontGate
    await route.continue()
  })
  try {
    await page.goto('/', { waitUntil: 'domcontentloaded' })
    const slot = page.locator('.scene-wrap')
    await expect(slot).toBeVisible()
    await expect(slot).toHaveText('')
    await expect(page.locator('.scene-loading, .atlas-fallback')).toHaveCount(0)
    await page.evaluate(() => document.fonts.ready)
    const before = await slot.boundingBox()
    releaseChunk()
    await fontRequest
    await expect(page.locator('.hero-canvas')).toBeHidden()
    await expect(slot).toHaveText('')
    await expect(page.getByRole('button', { name: 'Replay balloon inflation' })).toHaveCount(0)
    await page.screenshot({ path: testInfo.outputPath('loading-without-placeholder.png') })
    releaseFont()
    await expect(page.locator('.hero-scene.is-ready')).toBeVisible()
    await expect(page.locator('.hero-canvas')).toBeVisible()
    await expect(page.locator('.atlas-fallback')).toHaveCount(0)
    const after = await slot.boundingBox()
    expect(after!.height).toBe(before!.height)
    expect(after!.y).toBe(before!.y)
    await expect(page.locator('.hero-canvas')).toHaveAttribute('data-inflation', '100,100,100,100,100')
  } finally {
    releaseChunk()
    releaseFont()
  }
})

test('fallback lettering appears only if the balloon asset fails', async ({ page }) => {
  await page.route('**/balloon-font.json', (route) => route.abort())
  await page.goto('/')
  await expect(page.locator('.hero-scene.is-failed .atlas-fallback')).toBeVisible()
  await expect(page.locator('.atlas-fallback')).toHaveText('atlas')
  await expect(page.locator('.hero-canvas')).toBeHidden()
  await expect(page.getByRole('button', { name: 'Replay balloon inflation' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Leave a little love', exact: true })).toBeEnabled()
})

test('letters pop in a fresh random order, become foil balloons, and replay', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.locator('.hero-scene.is-ready')).toBeVisible()
  const initialOrder = await page.locator('.hero-canvas').getAttribute('data-pop-order')
  expect(initialOrder).not.toBe('0,1,2,3,4')
  expect(initialOrder).not.toBe('4,3,2,1,0')
  const replay = page.getByRole('button', { name: 'Replay balloon inflation' })
  await page.evaluate(() => Object.defineProperty(document, 'hidden', { configurable: true, get: () => true }))
  await replay.click()
  const replayOrder = await page.locator('.hero-canvas').getAttribute('data-pop-order')
  expect(replayOrder).not.toBe(initialOrder)
  expect(replayOrder).not.toBe('0,1,2,3,4')
  expect(replayOrder).not.toBe('4,3,2,1,0')
  const order = replayOrder!.split(',').map(Number)
  expect([...order].sort()).toEqual([0, 1, 2, 3, 4])
  await expect(page.locator('.hero-canvas')).toHaveAttribute('data-inflation', '0,0,0,0,0')
  const flat = await page.locator('.hero-scene canvas').evaluate((canvas: HTMLCanvasElement) => canvas.toDataURL())
  await page.locator('.scene-wrap').screenshot({ path: testInfo.outputPath('01-flat-letters.png') })
  await page.evaluate(() => Reflect.deleteProperty(document, 'hidden'))
  await page.waitForFunction(() => {
    const scene = document.querySelector<HTMLElement>('.hero-canvas')!
    const values = scene.dataset.inflation!.split(',').map(Number)
    const order = scene.dataset.popOrder!.split(',').map(Number)
    if (values[order[0]] >= 65 && values[order[4]] === 0) {
      Object.defineProperty(document, 'hidden', { configurable: true, get: () => true })
      return true
    }
    return false
  })
  const middle = await page.locator('.hero-canvas').getAttribute('data-inflation')
  const values = middle!.split(',').map(Number)
  expect(values[order[0]]).toBeGreaterThan(0)
  expect(values[order[4]]).toBe(0)
  for (let position = 1; position < order.length; position++) {
    expect(values[order[position - 1]]).toBeGreaterThanOrEqual(values[order[position]])
  }
  await page.locator('.scene-wrap').screenshot({ path: testInfo.outputPath('02-random-pop.png') })
  await page.evaluate(() => Reflect.deleteProperty(document, 'hidden'))
  await expect(page.locator('.hero-canvas')).toHaveAttribute('data-inflation', '100,100,100,100,100')
  await page.locator('.scene-wrap').screenshot({ path: testInfo.outputPath('03-foil-balloons.png') })
  const inflated = await page.locator('.hero-scene canvas').evaluate((canvas: HTMLCanvasElement) => canvas.toDataURL())
  expect(inflated).not.toBe(flat)
  const canvas = page.locator('.hero-scene canvas')
  const bounds = await canvas.boundingBox()
  await canvas.click({ position: { x: bounds!.width / 2, y: bounds!.height / 2 } })
  await expect(page.locator('.hero-canvas')).toHaveAttribute('data-inflation', /^100,100,\d{1,2},100,100$/)
  await page.evaluate(() => Object.defineProperty(document, 'hidden', { configurable: true, get: () => true }))
  await replay.focus()
  await page.keyboard.press('Enter')
  expect(await page.locator('.hero-canvas').getAttribute('data-pop-order')).not.toBe(replayOrder)
  await expect(page.locator('.hero-canvas')).toHaveAttribute('data-inflation', '0,0,0,0,0')
  await page.evaluate(() => Reflect.deleteProperty(document, 'hidden'))
})